### PR TITLE
Add support for rectangular aperture

### PR DESCRIPTION
**Pull request by mancausoft**
I have a gerber (generated with geda) with a rectangular aperture for a line. 
This patch fix for me the problem.

### CODE REVIEW

**Comment by kirberich** [comment]
There's potentially a slight problem with this because the rectangle starts right where the line starts, instead of a half aperture-width before the line starts / after the line ends. 

I might try and integrate this directly with the circle aperture stuff, gimme a minute :) Could you possibly send me the gerber files you're using so I can try this out?

**Comment by mancausoft** [comment]
Yes it is created from a opensource project (scsi2sd) so i think I can upload it.
[scsi2sd.toppaste.gbr.zip](https://github.com/kirberich/gerber_to_scad/files/169147/scsi2sd.toppaste.gbr.zip)

**Comment by kirberich** [comment]
Sorry could you send the outline file as well? I think I've got it fixed, I just want to make sure it actually outputs something sensible.

**Comment by mancausoft** [comment]
[scsi2sd.outline.gbr.zip](https://github.com/kirberich/gerber_to_scad/files/169164/scsi2sd.outline.gbr.zip)

**Comment by kirberich** [comment]
Right, this turned out to be a lot more complicated than I thought, but I think it works now. Let me know if I broke anything, I might not be able to look at it until tonight though.

The script seems to work fine with your board now, I'll update the site momentarily.

Thanks for your help, this uncovered a lot of broken in my code!

**Comment by kirberich** [comment]
Actually the site still seems to have some problems with it - I'm not sure why. The script works fine though, at least on my machine. Let me know if you have any more issues, and I'll look into it some more later.

**Comment by kirberich** [comment]
Sorry for spamming, just one more update: it seems different versions of OpenScad have different degrees of pickiness when it comes to the mesh, the version on the site fails, because of some overlapping shapes, but you can make it work by setting the "Increase the size of all holes" option by some tiny amount, like 0.005mm.

Hope this helps!

**Pull request merged**
